### PR TITLE
Automate pulling new components version

### PR DESCRIPTION
**Pull request by koplo199**
See the entire discussion in https://github.com/bottlesdevs/Bottles/issues/2223

TODO before merging:

- [ ] Fork [koplo199/actions-download-asset](https://github.com/koplo199/actions-download-asset) in the [bottlesdevs](https://github.com/bottlesdevs) organization. It is the action used to find and pull new stable versions. Forking is _mandatory_ as [upstream](https://github.com/blauqs/actions-download-asset) is not vastly used, contains multiple bugs, outdated dependencies, and is lacking required features.
- [ ] Fork [koplo199/action-gh-release](https://github.com/koplo199/action-gh-release) in the [bottlesdevs](https://github.com/bottlesdevs) organization. It is the action used to upload archives when required. Forking is _strongly advised_ as [upstream](https://github.com/softprops/action-gh-release) has outdated dependencies and its maintainer hasn't been active since april. However in its current state it is functional and is vastly used, so forking is not mandatory. In fact, if [action-gh-release/pull/275](https://github.com/softprops/action-gh-release/pull/275) was merged, there would be no reason to fork it anymore.
- [ ] Add `PAT` as actions secret (see https://github.com/bottlesdevs/Bottles/issues/2223#issuecomment-1313701226)

Please do not accept new PR in the meantime (like #180), as it initially requires a lot of manual processing to create the adequate new files, and it would probably drive me insane having to do it again

### CODE REVIEW

**Comment by koplo199** [comment]
It is possible to monitor what would be the first pull request of the CI here: https://github.com/koplo199/components/pull/39

**Comment by mirkobrombin** [comment]
(still reviewing, I'm busy with other projects), about the 2 forks, are you going to maintain them? :D

**Comment by koplo199** [comment]
> (still reviewing, I'm busy with other projects), about the 2 forks, are you going to maintain them? :D

 :sweat_smile: 
 

Honestly: in the very long term, probably not.
And this is precisely why I will replace them by [GitHub CLI](https://cli.github.com/) commands in a future PR, from what I read it could be used to do the same things, while being officially endorsed by GitHub.

But I would like this PR to get merged first, as it will add some substantial complexity to the code I prefer to implement it in a distinct PR. Also, and I guess it's human, it will motivate me a lot more to work on it :angel:

**Comment by orowith2os** [comment]
One more thing, possibly wait for my other cleanup PRs before merging this, if it ever does get accepted.

**Comment by koplo199** [comment]
> One more thing, possibly wait for my other cleanup PRs before merging this, if it ever does get accepted.

I would prefer the other way around, thank you.

**Comment by orowith2os** [comment]
> > One more thing, possibly wait for my other cleanup PRs before merging this, if it ever does get accepted.
> 
> I would prefer the other way around, thank you.

Merging this before my PR would make it harder to clean up, since I'd then have to update your checker to use those new, updated paths for components.

Better to have the clean PR merged first, then this, so that it Just Works more or less immediately after being merged.

**Comment by koplo199** [comment]
> Merging this before my PR would make it harder to clean up, since I'd then have to update your checker to use those new, updated paths for components.

And merging the clean up before this PR would make it harder to update my checker, since I'd then have to use your new, updated paths for components.

**Review by mirkobrombin — APPROVED** [review]

**Comment by mirkobrombin** [comment]
Everything looks fine and ready for merge. Just to be sure, this doesn't require Bottles side changes right?

**Comment by koplo199** [comment]
> Everything looks fine and ready for merge. Just to be sure, this doesn't require Bottles side changes right?

Nope!

**Comment by koplo199** [comment]
Yay merged :tada: 

@mirkobrombin I see that the two actions are not forked into the bottlesdevs organization (meaning the CI will fail tomorrow at 7:07AM or on a manual trigger), how do you want to handle this? I'm kinda bad at estimating, but I think I'll be able to fully replace them with Github CLI in less than a month, with that information if you think it doesn't make sense to fork it another option is to use my repo in the meantime by editing:

https://github.com/bottlesdevs/components/blob/fa879cd539bc8f00b4ba47366bbd972a5d18084b/.github/workflows/pull-components.yml#L53

https://github.com/bottlesdevs/components/blob/fa879cd539bc8f00b4ba47366bbd972a5d18084b/.github/workflows/pull-components.yml#L150

Same thing for the `PAT`, if not configured pull requests won't be created, to configure it:

From any account (could very well be a burner account)
`(Account) Settings -> Developer settings -> Personal access tokens -> Tokens (classic) -> Generate new token (classic) -> public_repo (No expiration)`

Then copy paste it into:
`(Repository) Settings -> Secrets -> Actions -> New repository secret -> Name = PAT`

**Pull request merged**
